// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm0WmvSzO3tl0vstOmNISxF5VSeJlPYhc',
    appId: '1:844523125865:web:d22ceab4a614d584ce36f8',
    messagingSenderId: '844523125865',
    projectId: 'online-shopping-app-161bf',
    authDomain: 'online-shopping-app-161bf.firebaseapp.com',
    storageBucket: 'online-shopping-app-161bf.firebasestorage.app',
    measurementId: 'G-BSW1VSWT4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ_a3502PgxhiVhGzkcdXYEIAsGbKpSho',
    appId: '1:844523125865:android:f8c2f78a285b88bece36f8',
    messagingSenderId: '844523125865',
    projectId: 'online-shopping-app-161bf',
    storageBucket: 'online-shopping-app-161bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClEhw2MIWBJo373RKpyYQKht7Ls6HWKtY',
    appId: '1:844523125865:ios:394a3cd2be328a54ce36f8',
    messagingSenderId: '844523125865',
    projectId: 'online-shopping-app-161bf',
    storageBucket: 'online-shopping-app-161bf.firebasestorage.app',
    iosBundleId: 'com.example.onlineShoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClEhw2MIWBJo373RKpyYQKht7Ls6HWKtY',
    appId: '1:844523125865:ios:394a3cd2be328a54ce36f8',
    messagingSenderId: '844523125865',
    projectId: 'online-shopping-app-161bf',
    storageBucket: 'online-shopping-app-161bf.firebasestorage.app',
    iosBundleId: 'com.example.onlineShoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm0WmvSzO3tl0vstOmNISxF5VSeJlPYhc',
    appId: '1:844523125865:web:d39a875d0e5ad3b3ce36f8',
    messagingSenderId: '844523125865',
    projectId: 'online-shopping-app-161bf',
    authDomain: 'online-shopping-app-161bf.firebaseapp.com',
    storageBucket: 'online-shopping-app-161bf.firebasestorage.app',
    measurementId: 'G-D3Z47XR38L',
  );
}
